export type SiteLocale = 'en' | 'tr' | 'de';

export function normalizeLocale(locale: string): SiteLocale {
  return locale === 'tr' || locale === 'de' ? locale : 'en';
}

export function getSiteCopy(locale: string) {
  return siteCopy[normalizeLocale(locale)];
}

export const siteCopy = {
  en: {
    nav: {
      app: 'App',
      business: 'Business',
      contact: 'Contact',
      signUp: 'Sign up',
      openMenu: 'Open menu',
      selectLanguage: 'Select language',
    },
    footer: {
      app: 'App',
      business: 'Business',
      about: 'About us',
      contact: 'Contact',
      legal: 'Privacy & legal',
    },
    app: {
      cards: {
        rooftop: 'LIVE AT ROOFTOP',
        matched: 'MATCHED TONIGHT',
        sameVenue: 'SAME VENUE',
        live: 'LIVE',
      },
      heroTitleA: 'Check-in.',
      heroTitleB: 'Match.',
      heroTitleC: 'Meet.',
      heroDescription: "Discover who's at the same venue or event before the night begins.",
      vibeTitleA: 'Let us help you find your',
      vibeTitleAccent: 'vibe',
      vibeDescription: 'Browse curated local events and venues where your kind of people are already hanging out.',
      googleSmall: 'GET IT ON',
      appleSmall: 'Download on the',
      howEyebrow: 'HOW IT WORKS',
      howTitle: 'From plan to people in three taps',
      howSteps: ['Find your event', 'Make your check-in', 'Meet the people'],
      crowdTitleA: 'Find out where the',
      crowdTitleAccent: 'crowd',
      crowdTitleB: 'is',
      crowdDescription: 'All events in one app. People are here too.',
    },
    business: {
      eyebrow: 'BOUNCINN BUSINESS',
      heroTitle: 'Run your venue from one live dashboard',
      heroDescription:
        "Running a venue usually feels like juggling ten glass balls at once. Currently, your data and operations are scattered everywhere-and that's exactly where you're losing money.",
      systemEyebrow: 'WHAT THE SYSTEM DOES',
      systemTitle: 'One system for every moving part of the night',
      features: [
        {
          eyebrow: 'LIVE OPERATIONS',
          title: 'See the pulse of your venue',
          accent: 'pulse',
          description: 'Track guests, check-ins, favorites, subscriptions and no-shows from one real-time overview built for busy nights.',
        },
        {
          eyebrow: 'GUEST LIST',
          title: 'Manage every guest without the chaos',
          accent: 'guest',
          description: 'Keep guest requests, arrivals and list status organized so your door team and managers stay in sync.',
        },
        {
          eyebrow: 'PROMOTERS',
          title: 'Know which promoters actually perform',
          accent: 'perform',
          description: 'Monitor promoter output, guest flow and campaign contribution without chasing screenshots or scattered spreadsheets.',
        },
        {
          eyebrow: 'PROMOTIONS',
          title: 'Launch offers when the room needs energy',
          accent: 'offers',
          description: 'Create targeted promotions and push timely campaigns to the people most likely to show up tonight.',
        },
        {
          eyebrow: 'TARGETING',
          title: 'Reach the right crowd, not just more people',
          accent: 'crowd',
          description: 'Use event behavior and venue data to understand who to invite, when to reach them and what will move them.',
        },
      ],
      trust: [
        ['Private venue data', 'Keep your venue data structured, separated and ready for smarter decisions.'],
        ['API ready', 'Connect Bouncinn Business to the tools your team already uses.'],
        ['Built to scale', 'Support multiple nights, venues and campaigns without rebuilding your workflow.'],
      ],
      walkthroughEyebrow: 'READY FOR A LIVE WALKTHROUGH?',
      walkthroughTitle: 'See how Bouncinn Business fits your venue.',
      contactEyebrow: 'GET IN TOUCH',
      contactTitle: "Let's talk about your venue.",
      contactDescription: 'Fill out the form below and our team will follow up with a demo and pricing tailored to your business.',
    },
    contact: {
      eyebrow: 'CONTACT BOUNCINN',
      title: "Let's build the next night out.",
      description: "Whether you're running a venue, planning a launch, or just curious about Bouncinn, send us a note and we'll get back to you.",
      exploreBusiness: 'Explore Business',
      cards: [
        ['Product questions', 'Ask about the app experience, events, venues, matching or future city launches.'],
        ['Venue demos', 'Request a walkthrough for Bouncinn Business and see how it fits your operation.'],
        ['Partnerships', 'Tell us about collaborations, event ideas or ways Bouncinn can support your crowd.'],
      ],
    },
    about: {
      eyebrow: 'ABOUT BOUNCINN',
      title: 'We make nights out feel alive before they begin.',
      description:
        'Bouncinn connects people, venues and events in one social layer. Discover where the energy is, check in with intent, and meet people who are already part of the same moment.',
      appCta: 'Explore the app',
      businessCta: 'For venues',
      principles: [
        ['Built around real places', 'Bouncinn starts with venues and events, because social discovery feels better when it is anchored in a real night out.'],
        ['People before profiles', 'The product is designed to make introductions feel contextual, timely and less random than endless swiping.'],
        ['Operations matter', 'For venues, Bouncinn Business turns nightlife energy into clearer data, smoother guest flow and better decisions.'],
      ],
      whyEyebrow: 'WHY IT EXISTS',
      whyTitle: 'Nightlife has data. It also has feeling.',
      whyBodyA:
        'We are building for both sides of the door: guests who want better context before they go out, and venues that need a sharper understanding of who is coming, what is working and where the energy is moving.',
      whyBodyB:
        'The result is a product family that connects discovery, check-ins, social presence and venue operations without losing the pulse of the night.',
    },
    form: {
      name: 'Full name',
      email: 'Email',
      message: 'Message',
      namePlaceholder: 'John Doe',
      emailPlaceholder: 'john@example.com',
      messagePlaceholder: 'How can we help?',
      submit: 'Send',
      sending: 'Sending...',
      successTitle: 'Message sent!',
      successDescription: 'We will get back to you shortly.',
      error: 'Something went wrong. Please try again.',
    },
  },
  tr: {
    nav: {
      app: 'Uygulama',
      business: 'Business',
      contact: 'İletişim',
      signUp: 'Kayıt ol',
      openMenu: 'Menüyü aç',
      selectLanguage: 'Dil seç',
    },
    footer: {
      app: 'Uygulama',
      business: 'Business',
      about: 'Hakkımızda',
      contact: 'İletişim',
      legal: 'Gizlilik ve yasal',
    },
    app: {
      cards: {
        rooftop: 'ROOFTOPTA CANLI',
        matched: 'BU GECE EŞLEŞTİ',
        sameVenue: 'AYNI MEKAN',
        live: 'CANLI',
      },
      heroTitleA: 'Check-in.',
      heroTitleB: 'Match.',
      heroTitleC: 'Meet.',
      heroDescription: 'Gece başlamadan önce aynı mekan veya etkinlikte kimlerin olduğunu keşfet.',
      vibeTitleA: 'Tarzını bulmana yardım edelim',
      vibeTitleAccent: '',
      vibeDescription: 'Senin tarzındaki insanların zaten takıldığı seçilmiş yerel etkinlikleri ve mekanları keşfet.',
      googleSmall: 'GOOGLE PLAY',
      appleSmall: 'App Store’dan',
      howEyebrow: 'NASIL ÇALIŞIR',
      howTitle: 'Plandan insanlara üç dokunuşta',
      howSteps: ['Etkinliğini bul', 'Check-in yap', 'İnsanlarla tanış'],
      crowdTitleA: 'Kalabalığın nerede olduğunu',
      crowdTitleAccent: 'keşfet',
      crowdTitleB: '',
      crowdDescription: 'Tüm etkinlikler tek uygulamada. İnsanlar da burada.',
    },
    business: {
      eyebrow: 'BOUNCINN BUSINESS',
      heroTitle: 'Mekanını tek bir canlı panelden yönet',
      heroDescription:
        'Bir mekanı yönetmek çoğu zaman aynı anda on cam topu çevirmek gibidir. Verilerin ve operasyonların farklı yerlere dağılmışsa, para kaybettiğin yer tam da burasıdır.',
      systemEyebrow: 'SİSTEM NE YAPAR',
      systemTitle: 'Gecenin tüm hareketli parçaları için tek sistem',
      features: [
        {
          eyebrow: 'CANLI OPERASYON',
          title: 'Mekanının nabzını gör',
          accent: 'nabzını',
          description: 'Yoğun geceler için tasarlanmış tek canlı panelden misafirleri, check-inleri, favorileri, abonelikleri ve gelmeyenleri takip et.',
        },
        {
          eyebrow: 'MİSAFİR LİSTESİ',
          title: 'Her misafiri karmaşa olmadan yönet',
          accent: 'misafiri',
          description: 'Misafir taleplerini, gelişleri ve liste durumunu düzenli tut; kapı ekibin ve yöneticilerin aynı sayfada kalsın.',
        },
        {
          eyebrow: 'PROMOTERLAR',
          title: 'Hangi promoterların gerçekten performans gösterdiğini bil',
          accent: 'performans',
          description: 'Promoter çıktısını, misafir akışını ve kampanya katkısını ekran görüntüleri veya dağınık tablolar peşinde koşmadan izle.',
        },
        {
          eyebrow: 'PROMOSYONLAR',
          title: 'Odanın enerjiye ihtiyacı olduğunda teklifleri başlat',
          accent: 'teklifleri',
          description: 'Hedefli promosyonlar oluştur ve bu gece gelme ihtimali en yüksek kişilere zamanında kampanyalar gönder.',
        },
        {
          eyebrow: 'HEDEFLEME',
          title: 'Daha fazla kişiye değil, doğru kalabalığa ulaş',
          accent: 'doğru',
          description: 'Kimi davet edeceğini, ne zaman ulaşacağını ve neyin harekete geçireceğini anlamak için etkinlik davranışını ve mekan verisini kullan.',
        },
      ],
      trust: [
        ['Özel mekan verisi', 'Mekan verini düzenli, ayrılmış ve daha akıllı kararlar için hazır tut.'],
        ['API’ye hazır', 'Bouncinn Business’ı ekibinin zaten kullandığı araçlara bağla.'],
        ['Büyümeye hazır', 'İş akışını yeniden kurmadan birden fazla geceyi, mekanı ve kampanyayı destekle.'],
      ],
      walkthroughEyebrow: 'CANLI BİR TANITIMA HAZIR MISIN?',
      walkthroughTitle: 'Bouncinn Business’ın mekanına nasıl uyduğunu gör.',
      contactEyebrow: 'İLETİŞİME GEÇ',
      contactTitle: 'Mekanını konuşalım.',
      contactDescription: 'Aşağıdaki formu doldur; ekibimiz işletmene özel demo ve fiyatlandırma için sana dönüş yapsın.',
    },
    contact: {
      eyebrow: 'BOUNCINN İLETİŞİM',
      title: 'Bir sonraki geceyi birlikte inşa edelim.',
      description: 'Mekan yönetiyor, bir lansman planlıyor ya da Bouncinn’i merak ediyor olabilirsin. Bize yaz, sana geri dönelim.',
      exploreBusiness: 'Business’ı keşfet',
      cards: [
        ['Ürün soruları', 'Uygulama deneyimi, etkinlikler, mekanlar, eşleşme veya yeni şehir lansmanları hakkında sor.'],
        ['Mekan demoları', 'Bouncinn Business için bir tanıtım iste ve operasyonuna nasıl uyduğunu gör.'],
        ['İş birlikleri', 'İş birliklerini, etkinlik fikirlerini veya Bouncinn’in kalabalığını nasıl destekleyebileceğini anlat.'],
      ],
    },
    about: {
      eyebrow: 'BOUNCINN HAKKINDA',
      title: 'Geceleri daha başlamadan canlı hissettiriyoruz.',
      description:
        'Bouncinn insanları, mekanları ve etkinlikleri tek bir sosyal katmanda buluşturur. Enerjinin nerede olduğunu keşfet, niyetle check-in yap ve aynı anın parçası olan insanlarla tanış.',
      appCta: 'Uygulamayı keşfet',
      businessCta: 'Mekanlar için',
      principles: [
        ['Gerçek mekanlar üzerine kuruldu', 'Bouncinn mekanlar ve etkinliklerle başlar; çünkü sosyal keşif gerçek bir geceye bağlı olduğunda daha iyi hissettirir.'],
        ['Profillerden önce insanlar', 'Ürün, tanışmaları bağlamlı, zamanında ve sonsuz kaydırmadan daha az rastgele hissettirmek için tasarlandı.'],
        ['Operasyon önemlidir', 'Mekanlar için Bouncinn Business, gece hayatı enerjisini daha net veriye, daha akıcı misafir akışına ve daha iyi kararlara dönüştürür.'],
      ],
      whyEyebrow: 'NEDEN VAR',
      whyTitle: 'Gece hayatının verisi var. Bir de hissi var.',
      whyBodyA:
        'Kapının iki tarafı için de inşa ediyoruz: dışarı çıkmadan önce daha iyi bağlam isteyen misafirler ve kimin geldiğini, neyin çalıştığını, enerjinin nereye aktığını daha net anlaması gereken mekanlar.',
      whyBodyB:
        'Sonuç; keşfi, check-inleri, sosyal varlığı ve mekan operasyonlarını gecenin nabzını kaybetmeden birleştiren bir ürün ailesi.',
    },
    form: {
      name: 'Ad soyad',
      email: 'E-posta',
      message: 'Mesajın',
      namePlaceholder: 'John Doe',
      emailPlaceholder: 'john@example.com',
      messagePlaceholder: 'Nasıl yardımcı olabiliriz?',
      submit: 'Gönder',
      sending: 'Gönderiliyor...',
      successTitle: 'Mesaj gönderildi!',
      successDescription: 'Kısa süre içinde sana geri döneceğiz.',
      error: 'Bir şeyler ters gitti. Lütfen tekrar dene.',
    },
  },
  de: {
    nav: {
      app: 'App',
      business: 'Business',
      contact: 'Kontakt',
      signUp: 'Registrieren',
      openMenu: 'Menü öffnen',
      selectLanguage: 'Sprache auswählen',
    },
    footer: {
      app: 'App',
      business: 'Business',
      about: 'Über uns',
      contact: 'Kontakt',
      legal: 'Datenschutz & Rechtliches',
    },
    app: {
      cards: {
        rooftop: 'LIVE AUF DEM ROOFTOP',
        matched: 'HEUTE ABEND GEMATCHT',
        sameVenue: 'GLEICHER ORT',
        live: 'LIVE',
      },
      heroTitleA: 'Check-in.',
      heroTitleB: 'Match.',
      heroTitleC: 'Meet.',
      heroDescription: 'Entdecke, wer am selben Ort oder bei derselben Veranstaltung ist, bevor die Nacht beginnt.',
      vibeTitleA: 'Wir helfen dir, deinen',
      vibeTitleAccent: 'Vibe',
      vibeDescription: 'Entdecke kuratierte lokale Events und Venues, in denen deine Art von Menschen bereits unterwegs ist.',
      googleSmall: 'JETZT BEI',
      appleSmall: 'Laden im',
      howEyebrow: 'SO FUNKTIONIERT ES',
      howTitle: 'Vom Plan zu Menschen in drei Taps',
      howSteps: ['Finde dein Event', 'Mach deinen Check-in', 'Triff die Menschen'],
      crowdTitleA: 'Finde heraus, wo die',
      crowdTitleAccent: 'Crowd',
      crowdTitleB: 'ist',
      crowdDescription: 'Alle Events in einer App. Menschen sind auch da.',
    },
    business: {
      eyebrow: 'BOUNCINN BUSINESS',
      heroTitle: 'Verwalte deine Venue über ein Live-Dashboard',
      heroDescription:
        'Eine Venue zu betreiben fühlt sich oft an, als würdest du zehn Glaskugeln gleichzeitig jonglieren. Wenn Daten und Abläufe überall verstreut sind, verlierst du genau dort Geld.',
      systemEyebrow: 'WAS DAS SYSTEM MACHT',
      systemTitle: 'Ein System für alle beweglichen Teile der Nacht',
      features: [
        {
          eyebrow: 'LIVE-BETRIEB',
          title: 'Sieh den Puls deiner Venue',
          accent: 'Puls',
          description: 'Verfolge Gäste, Check-ins, Favoriten, Abos und No-Shows in einer Live-Übersicht, die für volle Nächte gebaut ist.',
        },
        {
          eyebrow: 'GÄSTELISTE',
          title: 'Verwalte jeden Gast ohne Chaos',
          accent: 'Gast',
          description: 'Halte Gästelisten, Ankünfte und Status sauber organisiert, damit Türteam und Management synchron bleiben.',
        },
        {
          eyebrow: 'PROMOTER',
          title: 'Erkenne, welche Promoter wirklich performen',
          accent: 'performen',
          description: 'Überwache Promoter-Leistung, Gästefluss und Kampagnenbeitrag ohne Screenshots oder verstreute Tabellen.',
        },
        {
          eyebrow: 'PROMOTIONS',
          title: 'Starte Angebote, wenn der Raum Energie braucht',
          accent: 'Angebote',
          description: 'Erstelle gezielte Promotions und sende zeitnahe Kampagnen an die Menschen, die heute Abend am ehesten auftauchen.',
        },
        {
          eyebrow: 'TARGETING',
          title: 'Erreiche die richtige Crowd, nicht nur mehr Menschen',
          accent: 'richtige',
          description: 'Nutze Event-Verhalten und Venue-Daten, um zu verstehen, wen du einladen solltest, wann du sie erreichst und was sie bewegt.',
        },
      ],
      trust: [
        ['Private Venue-Daten', 'Halte deine Venue-Daten strukturiert, getrennt und bereit für bessere Entscheidungen.'],
        ['API-bereit', 'Verbinde Bouncinn Business mit den Tools, die dein Team bereits nutzt.'],
        ['Skalierbar gebaut', 'Unterstütze mehrere Nächte, Venues und Kampagnen, ohne deinen Workflow neu aufzubauen.'],
      ],
      walkthroughEyebrow: 'BEREIT FÜR EINEN LIVE-WALKTHROUGH?',
      walkthroughTitle: 'Sieh, wie Bouncinn Business zu deiner Venue passt.',
      contactEyebrow: 'KONTAKT AUFNEHMEN',
      contactTitle: 'Lass uns über deine Venue sprechen.',
      contactDescription: 'Fülle das Formular aus und unser Team meldet sich mit einer Demo und Preisen, die zu deinem Business passen.',
    },
    contact: {
      eyebrow: 'KONTAKT ZU BOUNCINN',
      title: 'Lass uns die nächste Nacht gestalten.',
      description: 'Ob du eine Venue betreibst, einen Launch planst oder einfach neugierig auf Bouncinn bist: Schreib uns, wir melden uns.',
      exploreBusiness: 'Business entdecken',
      cards: [
        ['Produktfragen', 'Frag uns zur App-Erfahrung, Events, Venues, Matching oder zukünftigen Stadt-Launches.'],
        ['Venue-Demos', 'Fordere einen Walkthrough für Bouncinn Business an und sieh, wie es zu deinem Betrieb passt.'],
        ['Partnerschaften', 'Erzähl uns von Kooperationen, Event-Ideen oder davon, wie Bouncinn deine Crowd unterstützen kann.'],
      ],
    },
    about: {
      eyebrow: 'ÜBER BOUNCINN',
      title: 'Wir machen Nächte lebendig, bevor sie beginnen.',
      description:
        'Bouncinn verbindet Menschen, Venues und Events in einer sozialen Ebene. Entdecke, wo die Energie ist, checke bewusst ein und triff Menschen, die bereits Teil desselben Moments sind.',
      appCta: 'App entdecken',
      businessCta: 'Für Venues',
      principles: [
        ['Rund um echte Orte gebaut', 'Bouncinn beginnt mit Venues und Events, weil soziale Entdeckung besser funktioniert, wenn sie in einer echten Nacht verankert ist.'],
        ['Menschen vor Profilen', 'Das Produkt soll Kennenlernen kontextbezogen, zeitnah und weniger zufällig als endloses Swipen machen.'],
        ['Betrieb zählt', 'Für Venues verwandelt Bouncinn Business Nachtleben-Energie in klarere Daten, reibungsloseren Gästefluss und bessere Entscheidungen.'],
      ],
      whyEyebrow: 'WARUM ES UNS GIBT',
      whyTitle: 'Nachtleben hat Daten. Und auch Gefühl.',
      whyBodyA:
        'Wir bauen für beide Seiten der Tür: Gäste, die vor dem Ausgehen besseren Kontext wollen, und Venues, die besser verstehen müssen, wer kommt, was funktioniert und wohin sich die Energie bewegt.',
      whyBodyB:
        'Das Ergebnis ist eine Produktfamilie, die Discovery, Check-ins, soziale Präsenz und Venue-Betrieb verbindet, ohne den Puls der Nacht zu verlieren.',
    },
    form: {
      name: 'Vollständiger Name',
      email: 'E-Mail',
      message: 'Nachricht',
      namePlaceholder: 'John Doe',
      emailPlaceholder: 'john@example.com',
      messagePlaceholder: 'Wie können wir helfen?',
      submit: 'Senden',
      sending: 'Wird gesendet...',
      successTitle: 'Nachricht gesendet!',
      successDescription: 'Wir melden uns in Kürze bei dir.',
      error: 'Etwas ist schiefgelaufen. Bitte versuche es erneut.',
    },
  },
} as const;
